# Generated by Django 2.0.3 on 2018-07-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='house_name',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
